'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { z } from 'zod';
import { baseElementSchema, evolvedElementSchema } from '@/core/elements';
import { createEvolutionPathSchema, updateEvolutionPathSchema } from '@/core/schemas/evolution';
import { createSpeciesSchema, updateSpeciesSchema } from '@/core/schemas/species';
import {
  createPath,
  creaturesOnPath,
  deletePath,
  setDefaultPath,
  updatePath,
} from '@/db/queries/evolution';
import {
  createSpecies,
  deleteSpecies,
  setSpeciesForm,
  slugExists,
  updateSpecies,
} from '@/db/queries/species';
import { AdminAccessError, requireAdmin } from '@/lib/auth';
import { errorChain } from '@/lib/errors';
import { MAX_IMAGE_BYTES, imageStorage } from '@/lib/storage';

/**
 * Every mutation in the panel goes through here.
 *
 * Three rules hold in every single action, without exception:
 *   1. requireAdmin() first — the role is re-read from the database. The layout
 *      guard only decides what to render; a server action is addressable on its
 *      own, so it must protect itself.
 *   2. Zod validation on the raw input. The schemas are strict, so an extra
 *      field is a rejection, not a silently ignored value.
 *   3. Nothing derived is accepted from the form: the evolved element comes from
 *      the base element, the stored image name is generated server-side, and
 *      created_at / updated_at come from the database.
 */

export type ActionState = {
  ok: boolean;
  message?: string;
  fieldErrors?: Record<string, string[]>;
};

function fail(message: string, fieldErrors?: Record<string, string[]>): ActionState {
  return { ok: false, message, ...(fieldErrors ? { fieldErrors } : {}) };
}

/** Turns a thrown error into something a human can act on. */
function describe(error: unknown): ActionState {
  if (error instanceof AdminAccessError) return fail(error.message);

  const chain = errorChain(error);
  if (chain.includes('species_slug_key')) {
    return fail('Ya existe una especie con ese slug', { slug: ['Slug repetido'] });
  }
  if (chain.includes('evolution_paths_species_target_key')) {
    return fail('Esta especie ya tiene una vía hacia ese elemento');
  }
  if (chain.includes('evolution_paths_one_default_per_species')) {
    return fail('Esa especie ya tiene una vía por defecto');
  }
  if (chain.includes('foreign key constraint')) {
    return fail('No se puede borrar: hay filas que dependen de esto');
  }
  console.error(error);
  return fail('Algo falló al guardar. Mira la consola del servidor.');
}

const text = (form: FormData, key: string): string => String(form.get(key) ?? '').trim();
const int = (form: FormData, key: string): number => Number(form.get(key) ?? Number.NaN);
const bool = (form: FormData, key: string): boolean => form.get(key) === 'on';
const nullable = (value: string): string | null => (value.length > 0 ? value : null);

/**
 * The powers, as they arrive from the editor: one field holding JSON.
 *
 * Parsed HERE and nowhere else, and then handed to `effectListSchema` like any
 * other untrusted input. The editor draws valid rows, but the editor is a
 * browser: a hand-written payload has to meet the same schema the resolver reads
 * with, or the JSONB column would be the one place the server took the client's
 * word for it.
 */
function effectsFrom(form: FormData): unknown {
  const raw = text(form, 'effects');
  if (raw.length === 0) return [];
  try {
    return JSON.parse(raw) as unknown;
  } catch {
    throw new Error('La lista de poderes no llegó como JSON válido');
  }
}

/**
 * Stores an uploaded image and returns its key, or null when no file was chosen.
 * The stored name is generated by the adapter — never the client's filename.
 */
async function storeImage(form: FormData, field: string): Promise<string | null> {
  const file = form.get(field);
  if (!(file instanceof File) || file.size === 0) return null;
  if (file.size > MAX_IMAGE_BYTES) {
    throw new Error(`La imagen supera el máximo de ${MAX_IMAGE_BYTES / 1024 / 1024} MB`);
  }
  const stored = await imageStorage().put({
    prefix: 'species',
    filename: file.name,
    contentType: file.type,
    data: await file.arrayBuffer(),
  });
  return stored.key;
}

function flatten(error: z.ZodError): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  for (const issue of error.issues) {
    const key = issue.path.map(String).join('.') || 'form';
    (result[key] ??= []).push(issue.message);
  }
  return result;
}

export async function createSpeciesAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  let createdId: string;

  try {
    const admin = await requireAdmin();

    const parsed = createSpeciesSchema.safeParse({
      name: text(form, 'name'),
      slug: text(form, 'slug'),
      /** "none" is a choice, not an empty field: the species is born white. */
      baseElement: text(form, 'baseElement') === 'none' ? null : text(form, 'baseElement'),
      baseImagePath: await storeImage(form, 'baseImage'),
      baseHp: int(form, 'baseHp'),
      baseAttack: int(form, 'baseAttack'),
      baseDefense: int(form, 'baseDefense'),
      manaCost: int(form, 'manaCost'),
      description: nullable(text(form, 'description')),
      isPublished: bool(form, 'isPublished'),
      effects: effectsFrom(form),
    });
    if (!parsed.success) return fail('Revisa los campos marcados', flatten(parsed.error));

    if (await slugExists(parsed.data.slug)) {
      return fail('Ya existe una especie con ese slug', { slug: ['Slug repetido'] });
    }

    const row = await createSpecies(parsed.data, admin.id);
    createdId = row.id;
  } catch (error) {
    return describe(error);
  }

  revalidatePath('/admin/species');
  redirect(`/admin/species/${createdId}`);
}

export async function updateSpeciesAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  try {
    await requireAdmin();

    const id = text(form, 'id');
    const uploaded = await storeImage(form, 'baseImage');

    const parsed = updateSpeciesSchema.safeParse({
      id,
      name: text(form, 'name'),
      slug: text(form, 'slug'),
      baseHp: int(form, 'baseHp'),
      baseAttack: int(form, 'baseAttack'),
      baseDefense: int(form, 'baseDefense'),
      manaCost: int(form, 'manaCost'),
      description: nullable(text(form, 'description')),
      isPublished: bool(form, 'isPublished'),
      effects: effectsFrom(form),
      /** Absent means "keep the current image", not "clear it". */
      ...(uploaded ? { baseImagePath: uploaded } : {}),
    });
    if (!parsed.success) return fail('Revisa los campos marcados', flatten(parsed.error));

    if (parsed.data.slug && (await slugExists(parsed.data.slug, id))) {
      return fail('Ya existe una especie con ese slug', { slug: ['Slug repetido'] });
    }

    await updateSpecies(parsed.data);
    revalidatePath('/admin/species');
    revalidatePath(`/admin/species/${id}`);
    return { ok: true, message: 'Guardado' };
  } catch (error) {
    return describe(error);
  }
}

/**
 * One of the four awakened faces: the name and the drawing a stone reveals.
 *
 * Saved per face rather than all four at once, so uploading one image does not
 * make the admin re-pick the other three — and an absent file means "keep the
 * current drawing", exactly like the species' own image.
 */
export async function saveSpeciesFormAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  try {
    await requireAdmin();

    const speciesId = text(form, 'speciesId');
    const uploaded = await storeImage(form, 'formImage');

    const parsed = z
      .strictObject({
        speciesId: z.uuid(),
        element: baseElementSchema,
        name: z.string().trim().min(2).max(80).nullable(),
      })
      .safeParse({
        speciesId,
        element: text(form, 'element'),
        name: nullable(text(form, 'name')),
      });
    if (!parsed.success) return fail('Revisa la cara', flatten(parsed.error));

    await setSpeciesForm(parsed.data.speciesId, parsed.data.element, {
      name: parsed.data.name,
      ...(uploaded ? { imagePath: uploaded } : {}),
    });

    revalidatePath(`/admin/species/${parsed.data.speciesId}`);
    return { ok: true, message: 'Cara guardada' };
  } catch (error) {
    return describe(error);
  }
}

export async function deleteSpeciesAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  try {
    await requireAdmin();
    const parsed = z.strictObject({ id: z.uuid() }).safeParse({ id: text(form, 'id') });
    if (!parsed.success) return fail('Identificador no válido');
    await deleteSpecies(parsed.data.id);
  } catch (error) {
    return describe(error);
  }

  revalidatePath('/admin/species');
  redirect('/admin/species');
}

export async function createPathAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  try {
    await requireAdmin();

    const parsed = createEvolutionPathSchema.safeParse({
      speciesId: text(form, 'speciesId'),
      /** Only evolved elements are accepted; a base element has nowhere to go. */
      targetElement: evolvedElementSchema.parse(text(form, 'targetElement')),
      name: text(form, 'name'),
      description: nullable(text(form, 'description')),
      imagePath: await storeImage(form, 'image'),
      hpBonus: int(form, 'hpBonus'),
      attackBonus: int(form, 'attackBonus'),
      defenseBonus: int(form, 'defenseBonus'),
      sortOrder: int(form, 'sortOrder'),
      isDefault: false,
      effects: effectsFrom(form),
    });
    if (!parsed.success) return fail('Revisa los campos de la vía', flatten(parsed.error));

    await createPath(parsed.data);
    revalidatePath(`/admin/species/${parsed.data.speciesId}`);
    return { ok: true, message: 'Vía creada' };
  } catch (error) {
    return describe(error);
  }
}

/**
 * Edits a path that already exists — its bonuses and, above all, ITS POWERS.
 *
 * Without this a path's effects could only ever be set at creation, so tuning
 * the transformed form meant deleting the path — which is refused as soon as a
 * single creature has locked it in. `targetElement` is deliberately not editable
 * for the same reason the species' base element is not.
 */
export async function updatePathAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  try {
    await requireAdmin();

    const speciesId = text(form, 'speciesId');
    const uploaded = await storeImage(form, 'image');

    const parsed = updateEvolutionPathSchema.safeParse({
      id: text(form, 'pathId'),
      name: text(form, 'name'),
      description: nullable(text(form, 'description')),
      hpBonus: int(form, 'hpBonus'),
      attackBonus: int(form, 'attackBonus'),
      defenseBonus: int(form, 'defenseBonus'),
      sortOrder: int(form, 'sortOrder'),
      effects: effectsFrom(form),
      ...(uploaded ? { imagePath: uploaded } : {}),
    });
    if (!parsed.success) return fail('Revisa los campos de la vía', flatten(parsed.error));

    await updatePath(parsed.data);
    revalidatePath(`/admin/species/${speciesId}`);
    return { ok: true, message: 'Vía actualizada' };
  } catch (error) {
    return describe(error);
  }
}

export async function setDefaultPathAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  try {
    await requireAdmin();
    const parsed = z
      .strictObject({ pathId: z.uuid(), speciesId: z.uuid() })
      .safeParse({ pathId: text(form, 'pathId'), speciesId: text(form, 'speciesId') });
    if (!parsed.success) return fail('Identificador no válido');

    await setDefaultPath(parsed.data.pathId, parsed.data.speciesId);
    revalidatePath(`/admin/species/${parsed.data.speciesId}`);
    return { ok: true, message: 'Vía por defecto actualizada' };
  } catch (error) {
    return describe(error);
  }
}

export async function deletePathAction(
  _prev: ActionState,
  form: FormData,
): Promise<ActionState> {
  try {
    await requireAdmin();
    const parsed = z
      .strictObject({ pathId: z.uuid(), speciesId: z.uuid() })
      .safeParse({ pathId: text(form, 'pathId'), speciesId: text(form, 'speciesId') });
    if (!parsed.success) return fail('Identificador no válido');

    /**
     * A locked choice is permanent, so a path a creature already committed to
     * cannot be deleted. The FK would refuse it anyway; this says why.
     */
    const inUse = await creaturesOnPath(parsed.data.pathId);
    if (inUse > 0) {
      return fail(`No se puede borrar: ${inUse} kriatura(s) ya eligieron esta vía`);
    }

    await deletePath(parsed.data.pathId);
    revalidatePath(`/admin/species/${parsed.data.speciesId}`);
    return { ok: true, message: 'Vía borrada' };
  } catch (error) {
    return describe(error);
  }
}
